name: 'Dependabot Auto-Merge'

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.token }}
